version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container-payment-qrcode
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pyqr
      MYSQL_USER: username
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: